# Generated by Django 3.2 on 2023-05-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(),
        ),
    ]
