# Generated by Django 3.2 on 2023-05-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
