# Generated by Django 3.2 on 2023-05-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_customuser_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='device',
        ),
    ]
