# Generated by Django 3.2 on 2023-04-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_users_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
        migrations.RemoveField(
            model_name='review',
            name='subject',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
