# Generated by Django 3.2 on 2023-04-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230417_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(default=1, max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
