# Generated by Django 3.2 on 2023-04-17 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20230417_2324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
